name: Codeball
on:
  pull_request: {}
  pull_request_review_comment:
    types: [created, edited]

jobs:
  codeball_job:
    runs-on: ubuntu-latest
    name: Codeball
    steps:
      # Run Codeball on all new Pull Requests and Review Comments! 🚀
      # For customizations and more documentation, see https://github.com/sturdy-dev/codeball-action
      - name: Codeball
        uses: sturdy-dev/codeball-action@v2
        with:
          approvePullRequests: "true"
          labelPullRequestsWhenApproved: "true"
          labelPullRequestsWhenReviewNeeded: "false"
          failJobsWhenReviewNeeded: "false"
          GITHUB_TOKEN: "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"
